### ISSUE TITLE
CST registro 54

### ISSUE THREAD

**Issue by robertorp** [AOPack/SINTEGRABr.NET#10]
![image](https://user-images.githubusercontent.com/10251705/45552734-4adc4980-b808-11e8-90d1-2f4cc5b8e371.png)

E somente CST ou CSOSN?

Quando for uma energia elétrica, os itens relacionados a ela entram aqui no registro 54 que é produto? ou energia elétrica eu lanço somente no registro 50 e pronto?

**Comment by samuelrochaoliveira** [comment]
Fala @robertorp, tudo na paz?

> E somente CST ou CSOSN?

O que o manual diz?
CAMPO 07 - preencher o campo conforme Tabelas A e B do Anexo Código de Situação Tributária do Convênio SINIEF s/nº de 1970.

No manual consta a previsão somente da CST, o SINTEGRA primariamente foi projetado para empresas contribuintes do ICMS e não optantes do SIMPLES, nunca fizeram o ajuste no layout para comportar CSOSN.

Mas por experiência própria lhe digo, ele aceita informar a CSOSN, e o Validador do Sintegra não acusa nenhum erro, só o programa do Validador do Paraná (VALIDA PR) que acusa esse tipo de informação.

> Quando for uma energia elétrica, os itens relacionados a ela entram aqui no registro 54 que é produto? ou energia elétrica eu lanço somente no registro 50 e pronto?

Nas observações do Registro Tipo 50 há a seguinte citação:
![image](https://user-images.githubusercontent.com/15462690/45553547-a4457800-b80a-11e8-8adb-5af326278117.png)

O Sintegra só obriga informar os itens da nota se for uma operação de venda ou compra de mercadorias para revenda, ou seja, o que é compra para imobilizado, ou consumo próprio não precisa ser criado no Registro Tipo 54, entende-se também que a energia elétrica é para uso do processo produtivo ou operacional da empresa, então, **não, não precisa ser informado no Registro Tipo 54, somente no Registro Tipo 50.**

Abraços.

**Comment by samuelrochaoliveira** [comment]
Fala @robertorp, tudo na paz? Conseguiu resolver teu problema?

Vou fechar a issue, caso tenha alguma dúvida é só reabrir, ok?

Abraços.
