### ISSUE TITLE
NF-e com 3 itens, sendo que dois itens tem o mesmo CFOP e um dos itens CFOP diferente

### ISSUE THREAD

**Issue by robertorp** [AOPack/SINTEGRABr.NET#11]
NF-e com 3 itens, sendo que dois itens tem o mesmo CFOP e um dos itens CFOP diferente
e os três tem alíquotas diferentes

Como gero o Registro 50 com base nisso?

Tenho uma revenda que me passou o seguinte

Gerar 3 Registros 50 são idênticos quase
Dois teriam o mesmo CFOP 
Um teria o CFOP diferente
Os três teriam alíquotas diferentes

e se por caso os três tivessem alíquotas iguais
eu teria que gerar 2 Registros 50 
Mudando apenas o CFOP 

Isso se aplica a tudo? Digo tem base de calculo também isso se aplica lá também?
Realmente e assim?

**Comment by robertorp** [comment]
Pelo que entendi a 
base de calculo
valor total
isenta ou não tributada
outras

são sobre os totais da NF-e e não sobre os itens 
então não geraria mais registros com eles 

mas com CFOP e alíquotas gerariam mais registros 50

**Comment by samuelrochaoliveira** [comment]
Fala @robertorp, tudo na paz?

Vamos lá...

Primeiramente, se o seu cliente só trabalha com documentos eletrônicos, entrada, saída, devolução etc, não precisa mais fazer SINTEGRA, pelo menos não no estado de Goiás. Segue abaixo:

![image](https://user-images.githubusercontent.com/15462690/46144134-7c0a4000-c232-11e8-80c7-7838ba1d2110.png)

> NF-e com 3 itens, sendo que dois itens tem o mesmo CFOP e um dos itens CFOP diferente
> e os três tem alíquotas diferentes
> 
> Como gero o Registro 50 com base nisso?

Para cada combinação CFOP - ALÍQUOTA você soma os valores, se for diferente cada um irá ficar em uma linha separado por CFOP e/ou ALÍQUOTA.

> Gerar 3 Registros 50 são idênticos quase
> Dois teriam o mesmo CFOP
> Um teria o CFOP diferente
> Os três teriam alíquotas diferentes

Aqui vai um exemplo:

![image](https://user-images.githubusercontent.com/15462690/46144355-0eaadf00-c233-11e8-94f9-cc18758959c8.png)

Para cada CFOP e/ou Alíquota diferente, você deve criar uma linha.

> e se por caso os três tivessem alíquotas iguais
> eu teria que gerar 2 Registros 50
> Mudando apenas o CFOP

Veja acima.

> Isso se aplica a tudo? Digo tem base de calculo também isso se aplica lá também?
> Realmente e assim?

Nesse sentido o SINTEGRA é bem parecido com o SPED Fiscal, lá também você tem que separar por CFOP e Alíquota, e tem a CST ainda que aqui no SINTEGRA não aparece.

Se tiver base de cálculo você só vai discriminar o valor nos campos corretos e não precisa criar uma linha só para dizer se tem ou não redução da base de cálculo, isento, outras. Vai tudo na mesma linha, desde que o CFOP e a Alíquota sejam únicos.

> Pelo que entendi a
> base de calculo
> valor total
> isenta ou não tributada
> outras
> 
> são sobre os totais da NF-e e não sobre os itens
> então não geraria mais registros com eles

Na verdade são sobre os itens, a soma dos itens irá originar esses valores. Tanto que se você informar um registro tipo 54 e ele não bater com os valores da nota o validador do sintegra vai te acusar um erro.

> mas com CFOP e alíquotas gerariam mais registros 50

Exato. Para cada combinação será uma linha.

Abraços.

**Comment by robertorp** [comment]
@samuelrochaoliveira  Obrigado! 
Sim, Goiás não tem, mas a empresa aqui atua fora, em MG e obrigatório para quem e optante do Simples Nacional (E tem outros 2 estados que são também, não me lembro quais são)
