### ISSUE TITLE
Teste Geração Sintegra Erro, Não encontrado registro tipo 50 correspondente. Registro 53

### ISSUE THREAD

**Issue by robertorp** [AOPack/SINTEGRABr.NET#12]
[sintegraTeste.txt](https://github.com/AOPack/SINTEGRABr.NET/files/2501415/sintegraTeste.txt)

Arquivo gerado de teste

Linha do erro 15 , esse registro 53 da linha 15 deveria ser vinculado ao registro 50 da linha 4
ai queria saber qual o vinculo entre os dois para estar corrigindo o mesmo

**Comment by robertorp** [comment]
encontrei o erro nos registro 55 
estava passando a série somente com 55.. e não 055 
feito isso foi corrigido

**Comment by samuelrochaoliveira** [comment]
Entendi. Precisando de ajuda é só falar. o/

Em seg, 22 de out de 2018 10:28 AM, Roberto Alves Pereira <
notifications@github.com> escreveu:
