### ISSUE TITLE
Integração

### ISSUE THREAD

**Issue by EdsonRodrigoBA** [AOPack/SINTEGRABr.NET#13]
Como faço para utilizar essa biblioteca em meu sistema ?
Quais classes devo usar para  pegar os dados do BD e gerar o arquivo.

**Comment by samuelrochaoliveira** [comment]
Fala @EdsonRodrigoBA  tudo em paz?

Para usar a lib basta baixar o projeto aqui no Github mesmo, compilar e referenciar a DLL de saída no seu projeto. Depois você deve "estruturar" o arquivo conforme a sua necessidade para cada informação da empresa. Basicamente são informações de documentos fiscais e produtos então você já deve ter tudo armazenado no seu banco de dados.

Na página inicial existem alguns exemplos de montagem do arquivo, dá uma olhada aqui no [readme](https://github.com/AOPack/SINTEGRABr.NET/blob/master/README.md).

Abraços.

**Comment by EdsonRodrigoBA** [comment]
Tem algum método que já salva o arquivo na pasta ?
Para simples nacional precisa quais registro precisam ?
Queria algum exemplo na pratica utilizando com DB.

**Comment by samuelrochaoliveira** [comment]
> Tem algum método que já salva o arquivo na pasta ?

O .NET Framework já tem esses métodos, Mas aqui na outra biblioteca do SPEDBr tem um exemplo de geração da Dimob, [clique aqui](https://github.com/AOPack/SPEDBr.NET/blob/master/SpedBr/SpedBr.Tests/DimobUnitTest.cs).

> Para simples nacional precisa quais registro precisam ?

Depende do seu estado, converse com o contador da empresa que ele poderá lhe ajudar.

> Queria algum exemplo na pratica utilizando com DB.

Se você souber consultar as informações do banco de dados não tem segredo.

Abraços.

**Comment by EdsonRodrigoBA** [comment]
Entendi, estou gerando, estou com duvidas referentes aos espaços.
Por exemplo no registro 54 o numero da nota são 6 digitos, e quando não tiver 6 dígitos como faço para acrescentar os zeros a esquerda o framework faz isso ?

**Comment by EdsonRodrigoBA** [comment]
Outra duvida também é em relação a NFE no REG54 , cada registro da NFE deve ter um numero sequencial iniciando em 01 02 etc.. Como que você trata isso ?
Exemplo sumos que tenho uma NFE numero 20 e ela possua dois registro 54.
teria que fica assim
registro 54  nf20 01
registro 54 nf20 02
Agora se eu tiver outra NFE 30 
teria que fica 
registro 54  nf30 01
registro 54 nf30 02
Não estou conseguindo implementar uma forma de fazer o numero sequencial no registro por NFE, entendeu?

**Comment by samuelrochaoliveira** [comment]
> Entendi, estou gerando, estou com duvidas referentes aos espaços.
> Por exemplo no registro 54 o numero da nota são 6 digitos, e quando não tiver 6 dígitos como faço para acrescentar os zeros a esquerda o framework faz isso ?

Fala @EdsonRodrigoBA no manual do SINTEGRA ele recomenda você utilizar somente os 6 últimos dígitos. Faz uma substring aí e puxa só os 6 finais.

![image](https://user-images.githubusercontent.com/15462690/60810836-59fc0180-a164-11e9-858a-dcef58289277.png)

**Comment by samuelrochaoliveira** [comment]
> Outra duvida também é em relação a NFE no REG54 , cada registro da NFE deve ter um numero sequencial iniciando em 01 02 etc.. Como que você trata isso ?
> Exemplo sumos que tenho uma NFE numero 20 e ela possua dois registro 54.
> teria que fica assim
> registro 54 nf20 01
> registro 54 nf20 02
> Agora se eu tiver outra NFE 30
> teria que fica
> registro 54 nf30 01
> registro 54 nf30 02
> Não estou conseguindo implementar uma forma de fazer o numero sequencial no registro por NFE, entendeu?

O Registro 54 é sobre PRODUTOS então ele pede um sequencial para cada produto que exista no documento fiscal, é simples, você vai fazer um foreach na lista de produtos e a cada vez que o laço se concluir você adiciona um número.

**Comment by EdsonRodrigoBA** [comment]
é um sequencial para cada produto de cada NFE , eu não to conseguindo fazer isso..se eu tiver mais de uma NFE emitida eu tenho que reiniciar  a sequencia..
entendeu, cmo você trata isso ?

**Comment by EdsonRodrigoBA** [comment]
pois da forma que tou fazendo ele esta gerando um numero sequencial, se tiver 300 registro e supomos que 150 registro é de uma nfe e 150 de outro ele fica sequencia de 1 a 300, queria que ficasse assim
nfe com 150 registro de 1 a 150 , depois o registro da segunda nf de 1 a 150 entendeu ?

**Comment by EdsonRodrigoBA** [comment]
Conseguir Gerar o Sintegra com sucesso pegando os dados do banco.
