### ISSUE TITLE
ATO COTEPE/ICMS N° 17, DE 29 DE MARÇO DE 2004

### ISSUE THREAD

**Issue by EdsonRodrigoBA** [AOPack/SINTEGRABr.NET#14]
Bom dia, 
Conhece alguma biblioteca C# para gerar os arquivo nesse layou ?
Registro E05, E08, E09, E10,E11,E12, E13, E14
https://www.confaz.fazenda.gov.br/legislacao/atos/2004/ac017_04

**Comment by osamueloliveira** [comment]
@EdsonRodrigoBA tudo em paz?
Não conheço nenhuma lib que faz mas se você quiser, pode fazer um pull request que eu aprovo e já fica tendo na biblioteca. Não é tão dificil mapear esses registros não.

**Comment by osamueloliveira** [comment]
Experimenta usar esse software aqui:
http://www.fazenda.mg.gov.br/empresas/ecf/informacoes/eecfc.htm

Abraços.

**Comment by EdsonRodrigoBA** [comment]
Boa tarde, entendi.
Vou verificar o link.
Obrigado pelo feedback.
