### ISSUE TITLE
NFC-e com Sintegra status, Canceladas, Denegadas é Numeração Inuitilizada

### ISSUE THREAD

**Issue by robertorp** [AOPack/SINTEGRABr.NET#15]
Bom para gerar Sintegra preciso dos registros 61 é 61R para NFC-e. 
Até então tudo bem, la nesses registros que vou adicionar somente NFC-e Autorizadas. 

Onde devo lançar NFC-e Cancelada, Denegada é Numeração Inutilizada para NFC-e ?

**Comment by osamueloliveira** [comment]
Fala @robertorp, tudo em paz?

Não precisa informar. O fisco já sabe do cancelamento ou inutilização então é redundante.

Basta informar as autorizadas, vide que o REG61 não tem campo para informar a situação do documento, certo? Logo, informe somente notas autorizadas.

Abraços.
