### ISSUE TITLE
Brancos, alguns registros tem isso 

### ISSUE THREAD

**Issue by robertorp** [AOPack/SINTEGRABr.NET#8]
![image](https://user-images.githubusercontent.com/10251705/45384084-6286b880-b5e3-11e8-9a0f-3509aaf777c3.png)

Isso e o mesmo que preencher de espaços ne?
enfim 
preciso realmente preencher com os espaços? ou o Framework já trata isso?

**Comment by samuelrochaoliveira** [comment]
Fala @robertorp,

A lib já trata isso.

A lib identifica qual o tipo do campo:
![image](https://user-images.githubusercontent.com/15462690/45384295-fd7f9280-b5e3-11e8-9892-4b317c49b28a.png)

E após preenche com a quantidade de casas esperadas (tendo valor ou não):
![image](https://user-images.githubusercontent.com/15462690/45384280-ee004980-b5e3-11e8-8f50-92773038174e.png)

Abraços.

**Comment by robertorp** [comment]
então não preciso me preocupar com essa propriedade 

![image](https://user-images.githubusercontent.com/10251705/45384428-6a932800-b5e4-11e8-97ac-db44d7d3dee3.png)

**Comment by samuelrochaoliveira** [comment]
Não.

![image](https://user-images.githubusercontent.com/15462690/45386489-d75cf100-b5e9-11e8-8888-fa3363fa0888.png)

O "valor" da propriedade já é definido ao instanciar o objeto.

**Comment by robertorp** [comment]
OK, obrigado.

**Comment by samuelrochaoliveira** [comment]
De nada. o/
