### ISSUE TITLE
Registro 70 , Data Emissao / Utilização

### ISSUE THREAD

**Issue by robertorp** [AOPack/SINTEGRABr.NET#9]
![image](https://user-images.githubusercontent.com/10251705/45489154-df2bab00-b739-11e8-898e-a86aea9ae975.png)

Prestador de serviço seria quando uma transportadora contrata outra transportadora?

"ou data de utilização do serviço para o tomador" Não sei o que é hehehe

**Comment by robertorp** [comment]
já entendi prestador de serviço seria 
a prestação de serviço, alguém contrata o serviço da transportadora. 

já a utilização do serviço para o tomador
e quando o tomador contrata o serviço mas não utilizou ele ainda, por algum motivo 

bom acho que é isso

**Comment by samuelrochaoliveira** [comment]
Na verdade o Registro Tipo 70 é "bilateral" como o Registro Tipo 50 (Nota Fiscais), server tanto para documentos de entrada ou saída, ou seja, se você é o prestador (a transportadora) vai informar a data de emissão. Se você é o tomador, quem recebe e/ou vai pagar pelo serviço, vai informar a data de utilização, eu destacaria a mesma data, para não ter que controlar quando chegou a mercadoria e colocar em data diversa. Mas é isso.

![image](https://user-images.githubusercontent.com/15462690/45490240-fc15ad80-b73c-11e8-8e88-f0c3634e21e5.png)

O tomador só irá informar esse registro se o tipo da operação for FOB.

Abraços.
